steps:
- name: 'gcr.io/cloud-builders/docker'
  script: |
    #!/usr/bin/env bash
    echo "your PR and Branch is: $_PR_NUMBER $BRANCH_NAME"
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', "gcloud secrets versions access latest --secret=pr-secret-id --format='get(payload.data)' | tr '_-' '/+' | base64 -d > token.txt" ]
- name: 'gcr.io/$PROJECT_ID/github'
  entrypoint: bash
  args: 
    - -c
    - | 
      echo "------------------GH AUTH------------------"
      gh auth login --with-token < token.txt
      echo "------------------Get PR Diff------------------"
      gh pr diff $_PR_NUMBER > /workspace/diff_string.txt
      echo "------------------PR Diff retrieved------------------"
- id: call-cloud-run-vertex-api
  name: gcr.io/cloud-builders/gcloud
  script: |
    echo "----------Teste VAR:"
    cat /workspace/diff_string.txt
    echo "------------------EOF------------------"
    diff_file_content=$(cat /workspace/diff_string.txt)
    echo "------------------Curl Cloud Run------------------"
    curl -X POST -H "Content-Type: application/json" -d '{ "code": $diff_file_content}' https://pr-review-o5id653ria-uc.a.run.app/pr_review | jq .
    echo "------------------End Cloud Run Response------------------"
options:
  automapSubstitutions: true
