steps:
- name: 'gcr.io/cloud-builders/docker'
  script: |
    #!/usr/bin/env bash
    echo "your PR and Branch is: $_PR_NUMBER $BRANCH_NAME"
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', "gcloud secrets versions access latest --secret=pr-secret-id --format='get(payload.data)' | tr '_-' '/+' | base64 -d > token.txt" ]
- name: 'gcr.io/$PROJECT_ID/github'
  entrypoint: bash
  args: 
    - -c
    - | 
      echo "------------------GH AUTH------------------"
      gh auth login --with-token < token.txt
      echo "------------------Get PR Diff------------------"
      gh pr diff $_PR_NUMBER > /workspace/diff_string.txt
      echo "------------------PR Diff retrieved------------------"
- id: call-cloud-run-vertex-api
  name: gcr.io/cloud-builders/gcloud
  script: |
    echo "----------Teste VAR:"
    cat /workspace/diff_string.txt
    echo "------------------EOF------------------"
    diff_string=$(cat /workspace/diff_string.txt)
    diff_file_content=$(echo "$diff_string" | base64)
    echo "{\"code\":\"$diff_file_content\"}" > /workspace/file.json 
    echo "------------------Curl Cloud Run------------------"
    curl -X POST -H "Content-Type: application/json"  --data @/workspace/file.json https://diff-review-qgbqdf7bda-uc.a.run.app/diff_review > /workspace/vertex_response.txt
    echo "------------------End Cloud Run Response------------------"
   
- id: comment_PR_Repo
  name: 'gcr.io/$PROJECT_ID/github'
  entrypoint: bash
  args: 
    - -c
    - | 
      echo "------------------GH AUTH------------------"
      gh auth login --with-token < token.txt
      echo "------------------Create PR Comment------------------"
      response_vertex=$(cat /workspace/vertex_response.txt)
      gh pr comment $_PR_NUMBER --body "Diff Review: $response_vertex"
      echo "------------------Comment inserted on PR------------------"
- id: call-cloud-run-vertex-api-sec
  name: gcr.io/cloud-builders/gcloud
  script: |
    echo "----------Teste VAR:"
    cat /workspace/diff_string.txt
    echo "------------------EOF------------------"
    diff_string=$(cat /workspace/diff_string.txt)
    diff_file_content=$(echo "$diff_string" | base64)
    echo "{\"code\":\"$diff_file_content\"}" > /workspace/file.json 
    echo "------------------Curl Cloud Run------------------"
    curl -X POST -H "Content-Type: application/json"  --data @/workspace/file.json https://sec-review-qgbqdf7bda-uc.a.run.app/sec_review > /workspace/vertex_sec_response.txt
    echo "------------------End Cloud Run Response------------------"
- id: comment_PR_Repo-sec
  name: 'gcr.io/$PROJECT_ID/github'
  entrypoint: bash
  args: 
    - -c
    - | 
      echo "------------------GH AUTH------------------"
      gh auth login --with-token < token.txt
      echo "------------------Create PR Comment------------------"
      response_vertex=$(cat /workspace/vertex_sec_response.txt)
      gh pr comment $_PR_NUMBER --body "Security Review: $response_vertex"
      echo "------------------Comment inserted on PR------------------"
- id: call-cloud-run-vertex-api-perf
  name: gcr.io/cloud-builders/gcloud
  script: |
    echo "----------Teste VAR:"
    cat /workspace/diff_string.txt
    echo "------------------EOF------------------"
    diff_string=$(cat /workspace/diff_string.txt)
    diff_file_content=$(echo "$diff_string" | base64)
    echo "{\"code\":\"$diff_file_content\"}" > /workspace/file.json 
    echo "------------------Curl Cloud Run------------------"
    curl -X POST -H "Content-Type: application/json"  --data @/workspace/file.json  https://us-central1-conventodapenha.cloudfunctions.net/perf_review > /workspace/vertex_perf_response.txt
    echo "------------------End Cloud Run Response------------------"
- id: comment_PR_Repo-perf
  name: 'gcr.io/$PROJECT_ID/github'
  entrypoint: bash
  args: 
    - -c
    - | 
      echo "------------------GH AUTH------------------"
      gh auth login --with-token < token.txt
      echo "------------------Create PR Comment------------------"
      response_vertex=$(cat /workspace/vertex_perf_response.txt)
      gh pr comment $_PR_NUMBER --body "Perf Review: $response_vertex"
      echo "------------------Comment inserted on PR------------------"
options:
  automapSubstitutions: true
