steps:
- name: 'gcr.io/cloud-builders/docker'
  script: |
    #!/usr/bin/env bash
    echo "your PR and Branch is: $_PR_NUMBER $BRANCH_NAME"
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', "gcloud secrets versions access latest --secret=pr-secret-id --format='get(payload.data)' | tr '_-' '/+' | base64 -d > token.txt" ]
- name: 'gcr.io/$PROJECT_ID/github'
  entrypoint: bash
  args: 
    - -c
    - | 
      set -e
      echo "------------------BLOCK------------------"
      gh auth login --with-token < token.txt
      echo "------------------BLOCK------------------"
      gh pr diff $_PR_NUMBER > /workspace/diff_string.txt
      echo "------------------BLOCK------------------"
- name: 'bash'
  script: |
    echo "Teste VAR:"
    cat /workspace/diff_string.txt
options:
  automapSubstitutions: true
