steps:
- name: 'gcr.io/cloud-builders/docker'
  script: |
    #!/usr/bin/env bash
    echo "your PR and Branch is: $_PR_NUMBER $BRANCH_NAME"
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', "gcloud secrets versions access latest --secret=pr-secret-id --format='get(payload.data)' | tr '_-' '/+' | base64 -d > token.txt" ]
- name: 'gcr.io/$PROJECT_ID/github'
  args: ['pr', 'diff', '$_PR_NUMBER -R https://github.com/duboc/pr-review']
options:
  automapSubstitutions: true